create table pokemon (
    pokemon_id integer generated by default as identity,
    name varchar(255) not null,
    type varchar(255) check (type in ('NORMAL','FIRE','WATER','ELECTRIC','GRASS','ICE','FIGHTING','POISON','GROUND','FLYING','PSYCHIC','BUG','ROCK','GHOST','DRAGON','DARK','STEEL','FAIRY')),
    primary key (pokemon_id)
);

create table review (
    pokemon_id integer,
    review_id integer generated by default as identity,
    stars integer not null,
    content varchar(255),
    title varchar(255) not null,
    primary key (review_id)
);

alter table if exists review add constraint FK_pokemon foreign key (pokemon_id) references pokemon;